// import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import { getCharacterItem, getCharacters, getRunningQueriesThunk } from '@/api/apiSlice';
import { wrapper } from '@/api/store';
import ErrorBoundary from '@/components/ErrorBoundary/ErrorBoundary';
import Header from '@/components/Header/Header';
import MainWrapper from '@/components/MainWrapper/MainWrapper';
// import { Provider } from 'react-redux';
// import { store } from '@/store/store';
import {
  ADDITIONAL_VALUE_PER_PAGE,
  BASE_URL,
  DEFAULT_PAGE,
} from '@/constants/constants';
import { store } from '@/store/store';
import { IData } from '@/types/types';
import { useRouter } from 'next/router';
import { Provider } from 'react-redux';

// This gets called on every request
// export async function getServerSideProps({
//   query: { name = '', page = 1, perPage = 20 },
// }: {
//   query: { name: string; page: number; perPage: number };
// }) {
//   // const router = useRouter()

//   // const currentPage =
//   // perPage === ADDITIONAL_VALUE_PER_PAGE && page > +DEFAULT_PAGE
//   //   ? Math.ceil(page / 2)
//   //   : page;

//   // const currentPage =
//   //         perPage === ADDITIONAL_VALUE_PER_PAGE && page > +DEFAULT_PAGE
//   //           ? Math.ceil(page / 2)
//   //           : page;

//   // console.log(name)
//   // console.log(query)
//   // console.log(context)page
//   // Fetch data from external API
//   const res = await fetch(`${BASE_URL}/?name=${name}&page=${page}`);
//   const data: IData = await res.json();

//   // Pass data to the page via props
//   return { props: { data } };
// }

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async (context) => {
    // console.log(store)
    // console.log(context)
    const id = context.params?.id;
    if (id) {
      store.dispatch(getCharacterItem.initiate({ id }));
    }
      store.dispatch(getCharacters.initiate({ query: '', currentPage: '1', perPage: '20' }));

    await Promise.all(store.dispatch(getRunningQueriesThunk()));

    return {
      props: {},
    };
  }
);

// if (typeof id === "string") {
//   store.dispatch(getCharacterItem.initiate({ id }));
// }

// await Promise.all(store.dispatch(getRunningQueriesThunk()));

export default function Page() {
  // console.log(props);
  // const router = useRouter()

  // useEffect(() => {
  //   router.push('/?page=1', undefined, { shallow: true })
  // }, [])

  // useEffect(() => {

  // }, [router.query.page])

  return (
      <Provider store={store}>
    <ErrorBoundary>
      <Header />
      <MainWrapper />
    </ErrorBoundary>
      </Provider>
  );
}

// const inter = Inter({ subsets: ['latin'] })

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={`${styles.main} ${inter.className}`}>
//         <div className={styles.description}>
//           <p>
//             Get started by editing&nbsp;
//             <code className={styles.code}>src/pages/index.tsx</code>
//           </p>
//           <div>
//             <a
//               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               By{' '}
//               <Image
//                 src="/vercel.svg"
//                 alt="Vercel Logo"
//                 className={styles.vercelLogo}
//                 width={100}
//                 height={24}
//                 priority
//               />
//             </a>
//           </div>
//         </div>

//         <div className={styles.center}>
//           <Image
//             className={styles.logo}
//             src="/next.svg"
//             alt="Next.js Logo"
//             width={180}
//             height={37}
//             priority
//           />
//         </div>

//         <div className={styles.grid}>
//           <a
//             href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Docs <span>-&gt;</span>
//             </h2>
//             <p>
//               Find in-depth information about Next.js features and&nbsp;API.
//             </p>
//           </a>

//           <a
//             href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Learn <span>-&gt;</span>
//             </h2>
//             <p>
//               Learn about Next.js in an interactive course with&nbsp;quizzes!
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Templates <span>-&gt;</span>
//             </h2>
//             <p>
//               Discover and deploy boilerplate example Next.js&nbsp;projects.
//             </p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//             target="_blank"
//             rel="noopener noreferrer"
//           >
//             <h2>
//               Deploy <span>-&gt;</span>
//             </h2>
//             <p>
//               Instantly deploy your Next.js site to a shareable URL
//               with&nbsp;Vercel.
//             </p>
//           </a>
//         </div>
//       </main>
//     </>
//   )
// }
